default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: blog_app_for_odnin_project_development

test:
  <<: *default
  database: blog_app_for_odnin_project_test

production:
  <<: *default
  database: blog_app_for_odnin_project_productions
  username: blog_app_for_odnin_project_username
  password: <%= ENV["OP_BLOG_APP_DATABASE_PASSWORD"]%>
